### ISSUE TITLE
Correct way to handle BLE Stack Error Code?

### ISSUE THREAD

**Issue by manikavi** [Fakher-Hakim/android-BluetoothLeGatt#1]
BLE Stack Error Code in Moto-G(5.1),Nexus(6.0.1)

22 is 0x16 which means connection terminated by local host. - Here  localhost means ANDROID DEVICE
8 is 0x8 which means connection timeout.
19 is 0x13 which means connection terminate by peer user. - Here peeruser means A&D BP,Scale devices

How I'm handling now?
gatt.disconnect();

-------------
How can I handle this in different way?

1.Is there any way to handle this issue other than disconnecting BluetoothGatt?(Just curious to know)

2.Shall I show popup to user that your values are stored in BP device,On next successful connection vital device will push your values automatically?

P.S: 

1.If we see from developer's perspective,we know that this is BLE Stack exception,By if we see from user's perspective,they will think ohhhh something wrong in android app,that is why it is not Showing my BP reading in android Screen.

**Comment by Fakher-Hakim** [comment]
UX is very important in Android development. if it's a frequent issue, you can make a second retry to get the value (don't forget to do this in background and showing a progress bar or something like that) if after two times value is not read from the device, you can show an error to the user and demand to try again. So with a second try (without the user know it) you can escape from this problem.
